apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler #scale the nginx container based on demand
metadata:
 name: nginx-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: nginx-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50